SELECT CONCAT('HELLO',' WORLD');

SELECT CONCAT(NAME,' BRON ON', DOB) AS INFO
FROM EMPLOYEE;

SELECT UPPER('hii i am abhishek') as upper;

SELECT LOWER('HII I AM ABHISHEK') AS LOWER;

SELECT TRIM('    HELLO   I AM ABHISHEK    ');

SELECT SUBSTR('I NEED A BREAK',6,9);

SELECT LENGTH('ABHISHEK NAIK');

SELECT CHAR_LENGTH('ABHISHEK NAIK 1234');

SELECT insert('ABHISHEK', 3, 4,'SONU');

SELECT instr('ABHISHEK',4);

SELECT REPEAT('HELLO DATABASE ',5);
/**/
SELECT REPLACE('HELLO DATABASE ','DATABASE','SQL');

/*Reverse the string*/
SELECT reverse('HELLO DATABASE');

/*check which is grearer*/
SELECT STRCMP('Database','Sql');
SELECT STRCMP('Sql','Database');

